const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function go(id){$$(".page").forEach(p=>p.classList.remove("active"));$("#"+id).classList.add("active");$("#drawer").style.display="none";scrollTo({top:0,behavior:"smooth"});burst()}
$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));$("#menu").onclick=()=>$("#drawer").style.display=$("#drawer").style.display==="block"?"none":"block";$("#enter").onclick=()=>go("events");
// Event cards / simple event menu
const eventModal=$("#eventModal"), modalTitle=$("#modalTitle"), modalText=$("#modalText"), modalKicker=$("#modalKicker"), modalMedia=$("#modalMedia");
const eventData={
  election:{kicker:"HIGHLIGHT • EVENT 01",title:"College Election",text:"Election information and the official poster will appear here.",image:"yimkongyatet.png"},
  event2:{kicker:"EVENT 02",title:"Academic Session",text:"More information for this event will be added here."},
  event3:{kicker:"EVENT 03",title:"Maths Activity",text:"More information for this event will be added here."}
};
function openEvent(key){const e=eventData[key];if(!e)return;modalKicker.textContent=e.kicker;modalTitle.textContent=e.title;modalText.textContent=e.text;modalMedia.innerHTML=e.image?`<img src="${e.image}" alt="${e.title}" onerror="this.style.display='none'">`:"";eventModal.classList.add("open");eventModal.setAttribute("aria-hidden","false")}
function closeEvent(){eventModal.classList.remove("open");eventModal.setAttribute("aria-hidden","true")}
$$('.event-button').forEach(b=>b.addEventListener('click',()=>openEvent(b.dataset.event)));
$("#closeEvent").addEventListener("click",closeEvent);
eventModal.addEventListener("click",e=>{if(e.target===eventModal)closeEvent()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeEvent()});

function burst(){for(let i=0;i<18;i++){let s=document.createElement("span");s.textContent=["π","∑","√","∞","Δ","∫","x²"][Math.floor(Math.random()*7)];s.style.cssText=`position:fixed;left:50%;top:50%;z-index:60;pointer-events:none;font-weight:900;font-size:${12+Math.random()*22}px;color:#17254a;transition:900ms ease-out`;document.body.append(s);requestAnimationFrame(()=>s.style.transform=`translate(${(Math.random()-.5)*500}px,${(Math.random()-.5)*500}px) rotate(${Math.random()*360}deg)`);setTimeout(()=>s.remove(),950)}}
let formulas=[
["Differentiation","Power Rule","d/dx(xⁿ) = nxⁿ⁻¹"],["Differentiation","Constant","d/dx(c) = 0"],["Differentiation","Product","(uv)' = u'v + uv'"],["Differentiation","Quotient","(u/v)' = (vu' − uv')/v²"],["Differentiation","Chain Rule","d/dx f(g(x)) = f'(g(x))g'(x)"],["Differentiation","Exponential","d/dx(eˣ) = eˣ"],["Differentiation","Logarithm","d/dx(ln x) = 1/x"],["Differentiation","Trig","(sin x)'=cos x; (cos x)'=−sin x"],["Integration","Power Rule","∫xⁿdx = xⁿ⁺¹/(n+1)+C, n≠−1"],["Integration","Basic","∫1 dx = x+C"],["Integration","Exponential","∫eˣdx = eˣ+C"],["Integration","Logarithm","∫1/x dx = ln|x|+C"],["Integration","By Parts","∫u dv = uv − ∫v du"],["Integration","Definite","∫ₐᵇ f(x)dx = F(b)−F(a)"],["Algebra","Quadratic","x = (−b ± √(b²−4ac))/(2a)"],["Algebra","AP","aₙ = a+(n−1)d; Sₙ=n/2[2a+(n−1)d]"],["Algebra","GP","aₙ=arⁿ⁻¹; Sₙ=a(rⁿ−1)/(r−1)"],["Trigonometry","Identity","sin²x + cos²x = 1"],["Trigonometry","Double Angle","sin 2x = 2sin x cos x"],["Coordinate Geometry","Distance","d=√[(x₂−x₁)²+(y₂−y₁)²]"],["Statistics","Mean","x̄ = Σx/n"],["Statistics","Variance","σ² = Σ(x−x̄)²/n"],["Statistics","Standard Deviation","σ = √σ²"],["Calculus","Taylor","f(x)=Σ f⁽ⁿ⁾(a)(x−a)ⁿ/n!"] ];
function renderFormulas(filter=""){const g=$("#formulaGrid");g.innerHTML=formulas.filter(x=>(x.join(" ")).toLowerCase().includes(filter.toLowerCase())).map(x=>`<article class="formula"><span class="tag">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("")}renderFormulas();$("#formulaSearch").oninput=e=>renderFormulas(e.target.value);
$$(".game-tabs button").forEach(b=>b.onclick=()=>{$$(".game-tabs button").forEach(x=>x.classList.remove("gactive"));b.classList.add("gactive");$$(".game").forEach(x=>x.classList.remove("activegame"));$("#"+b.dataset.game).classList.add("activegame")});
let score=0,timer;$("#start").onclick=()=>{score=0;$("#gscore").textContent=0;clearInterval(timer);let t=15;moveTarget();timer=setInterval(()=>{t--;if(t<=0){clearInterval(timer);$("#target").style.display="none";alert("Time! Score: "+score)}},1000);$("#target").style.display="block"};function moveTarget(){let a=$("#gameArena"),b=$("#target");b.style.left=Math.random()*88+"%";b.style.top=Math.random()*78+"%"}$("#target").onclick=()=>{score++;$("#gscore").textContent=score;moveTarget()};
const questions=[["What is d(x²)/dx?",["x","2x","x²"],1],["∫1 dx equals?",["x+C","1+C","ln x"],0],["sin²x + cos²x = ?",["0","2","1"],2],["√(b²−4ac) appears in?",["Quadratic formula","AP","Mean"],0]];let qi=0;function quiz(){let q=questions[qi];$("#qtext").textContent=q[0];$("#qanswers").innerHTML=q[1].map((x,i)=>`<button class="answer" data-i="${i}">${x}</button>`).join("");$$(".answer").forEach(b=>b.onclick=()=>{let ok=+b.dataset.i===q[2];$("#qresult").textContent=ok?"✓ Correct!":"✗ Try again.";if(ok){qi=(qi+1)%questions.length;setTimeout(quiz,600)}})}quiz();
const nums=[[7,8],[12,9],[15,6],[11,11],[14,7]];let ni=0;function nextCalc(){let n=nums[ni];$("#calcQ").textContent=`${n[0]} × ${n[1]} = ?`;$("#calcA").value=""}$("#check").onclick=()=>{let n=nums[ni],ok=+$("#calcA").value===n[0]*n[1];$("#calcResult").textContent=ok?"✓ Correct!":"✗ Try again.";if(ok){ni=(ni+1)%nums.length;nextCalc()}};nextCalc();
/* depth-like floating maths */
const canvas=$("#mathCanvas"),ctx=canvas.getContext("2d");let W,H,dots=[],mx=.5,my=.5;function resize(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;dots=Array.from({length:70},()=>({x:Math.random()*W,y:Math.random()*H,z:.2+Math.random()*.8,s:12+Math.random()*25,v:Math.random()*.35-.175,t:["π","∑","√","∞","Δ","∫","x²","θ","f(x)"][Math.floor(Math.random()*9)]}))}resize();addEventListener("resize",resize);addEventListener("pointermove",e=>{mx=e.clientX/innerWidth;my=e.clientY/innerHeight});function draw(){ctx.clearRect(0,0,W,H);dots.forEach(d=>{d.y+=d.v*d.z;if(d.y>H+50)d.y=-50;let x=d.x+(mx-.5)*70*d.z,y=d.y+(my-.5)*40*d.z;ctx.globalAlpha=.05+.14*d.z;ctx.fillStyle="#315889";ctx.font=`900 ${d.s*d.z+10}px Georgia`;ctx.fillText(d.t,x,y)});requestAnimationFrame(draw)}draw();